name: "Webhook Contract CI"
description: "Validate webhook payload samples against a baseline schema and detect breaking changes."
author: ""

inputs:
  mode:
    description: "check|diff"
    required: false
    default: "diff"
  schema:
    description: "Path to baseline JSON schema (checked into the repo)"
    required: true
  payload:
    description: "Path to webhook payload sample (JSON) to validate/diff"
    required: true
  show_nonbreaking:
    description: "If true, prints non-breaking additions/removals"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install wcci dependencies
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        npm ci --omit=dev

    - name: Run wcci
      shell: bash
      run: |
        MODE="${{ inputs.mode }}"

        # Inputs are expected to be relative to the repo root (GITHUB_WORKSPACE).
        # If an absolute path is provided, keep it as-is.
        if [[ "${{ inputs.schema }}" = /* ]]; then
          SCHEMA="${{ inputs.schema }}"
        else
          SCHEMA="$GITHUB_WORKSPACE/${{ inputs.schema }}"
        fi

        if [[ "${{ inputs.payload }}" = /* ]]; then
          PAYLOAD="${{ inputs.payload }}"
        else
          PAYLOAD="$GITHUB_WORKSPACE/${{ inputs.payload }}"
        fi

        EXTRA=""
        if [ "${{ inputs.show_nonbreaking }}" = "true" ]; then
          EXTRA="--show-nonbreaking"
        fi

        CLI="$GITHUB_ACTION_PATH/dist/cli.js"

        if [ "$MODE" = "check" ]; then
          node "$CLI" check --schema "$SCHEMA" --in "$PAYLOAD"
        else
          node "$CLI" diff --base "$SCHEMA" --next "$PAYLOAD" $EXTRA
        fi
